# EDA Milestone:
# Exploratory Data Analysis on AirBnB Dataset

## 1- Importing necessary packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2- Reading airbnb_nyc.csv file to open dataset

In [4]:
airbnb_nyc = pd.read_csv('airbnb_nyc.csv')
airbnb_nyc.head()

,id,name,summary,description,experiences_offered,neighborhood_overview,transit,house_rules,host_id,host_since,...,hot_tub_sauna_or_pool,internet,long_term_stays,pets_allowed,private_entrance,secure,self_check_in,smoking_allowed,accessible,event_suitable
0,2539,Clean & quiet apt home by the park,Renovated apt home in elevator building.,Renovated apt home in elevator building. Spaci...,none,Close to Prospect Park and Historic Ditmas Park,Very close to F and G trains and Express bus i...,-The security and comfort of all our guests is...,2787,39698.0,...,-1,1,1,-1,-1,1,1,-1,1,1
1,3647,THE VILLAGE OF HARLEM....NEW YORK !,NaN,WELCOME TO OUR INTERNATIONAL URBAN COMMUNITY T...,none,NaN,NaN,Upon arrival please have a legibile copy of yo...,4632,39777.0,...,-1,1,-1,-1,-1,-1,-1,-1,-1,-1
2,7750,Huge 2 BR Upper East Cental Park,NaN,Large Furnished 2BR one block to Central Park...,none,NaN,NaN,NaN,17985,39953.0,...,-1,1,-1,1,-1,-1,-1,-1,-1,-1
3,8505,Sunny Bedroom Across Prospect Park,Just renovated sun drenched bedroom in a quiet...,Just renovated sun drenched bedroom in a quiet...,none,Quiet and beautiful Windsor Terrace. The apart...,Ten minutes walk to the 15th sheet F&G train s...,- No shoes in the house - Quiet hours after 11...,25326,40006.0,...,-1,1,-1,-1,-1,-1,-1,-1,-1,-1
4,8700,Magnifique Suite au N de Manhattan - vue Cloitres,Suite de 20 m2 a 5 min des 2 lignes de metro a...,Suite de 20 m2 a 5 min des 2 lignes de metro a...,none,NaN,Metro 1 et A,NaN,26394,40014.0,...,-1,1,-1,-1,-1,-1,-1,-1,-1,-1

## 3- Looking at dataset detailes
> Checking features of the dataset helps to take look at the big picture and get an idea of how does it look like.

In [6]:
airbnb_nyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30179 entries, 0 to 30178
Data columns (total 81 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            30179 non-null  int64
 1   name                                          30166 non-null  object
 2   summary                                       28961 non-null  object
 3   description                                   29575 non-null  object
 4   experiences_offered                           30179 non-null  object
 5   neighborhood_overview                         18113 non-null  object
 6   transit                                       18190 non-null  object
 7   house_rules                                   16623 non-null  object
 8   host_id                                       30179 non-null  int64
 9   host_since                                    30170 non-null  float64
 10  host_response_time                            17082 non-null  object
 11  host_response_rate                            17082 non-null  float64
 12  host_is_superhost                             30170 non-null  float64
 13  host_listings_count                           30170 non-null  float64
 14  host_identity_verified                        30170 non-null  float64
 15  street                                        30179 non-null  object
 16  neighbourhood                                 30170 non-null  object
 17  latitude                                      30179 non-null  float64
 18  longitude                                     30179 non-null  float64
 19  property_type                                 30179 non-null  object
 20  room_type                                     30179 non-null  object
 21  accommodates                                  30179 non-null  int64
 22  bathrooms                                     30179 non-null  float64
 23  bedrooms                                      30179 non-null  int64
 24  beds                                          30179 non-null  int64
 25  bed_type                                      30179 non-null  object
 26  amenities                                     30179 non-null  object
 27  price                                         30179 non-null  int64
 28  guests_included                               30179 non-null  int64
 29  extra_people                                  30179 non-null  int64
 30  minimum_nights                                30179 non-null  int64
 31  calendar_updated                              30179 non-null  object
 32  has_availability                              30179 non-null  int64
 33  availability_30                               30179 non-null  int64
 34  availability_60                               30179 non-null  int64
 35  availability_90                               30179 non-null  int64
 36  availability_365                              30179 non-null  int64
 37  number_of_reviews                             30179 non-null  int64
 38  number_of_reviews_ltm                         30179 non-null  int64
 39  review_scores_rating                          21094 non-null  float64
 40  review_scores_accuracy                        21068 non-null  float64
 41  review_scores_cleanliness                     21078 non-null  float64
 42  review_scores_checkin                         21050 non-null  float64
 43  review_scores_communication                   21069 non-null  float64
 44  review_scores_location                        21047 non-null  float64
 45  review_scores_value                           21049 non-null  float64
 46  instant_bookable                              30179 non-null  int64
 47  cancellation_policy                           30179 non-null  object
 48  calculated_host_listings_count                30179 non-null  int64
 49  calculated_host_listings_count_entire_homes   30179 non-null  int64
 50  calculated_host_listings_count_private_rooms  30179 non-null  int64
 51  calculated_host_listings_count_shared_rooms   30179 non-null  int64
 52  reviews_per_month                             21919 non-null  float64
 53  check_in_24h                                  30179 non-null  int64
 54  air_conditioning                              30179 non-null  int64
 55  high_end_electronics                          30179 non-null  int64
 56  bbq                                           30179 non-null  int64
 57  balcony                                       30179 non-null  int64
 58  nature_and_views                              30179 non-null  int64
 59  bed_linen                                     30179 non-null  int64
 60  breakfast                                     30179 non-null  int64
 61  tv                                            30179 non-null  int64
 62  coffee_machine                                30179 non-null  int64
 63  cooking_basics                                30179 non-null  int64
 64  white_goods                                   30179 non-null  int64
 65  elevator                                      30179 non-null  int64
 66  gym                                           30179 non-null  int64
 67  child_friendly                                30179 non-null  int64
 68  parking                                       30179 non-null  int64
 69  outdoor_space                                 30179 non-null  int64
 70  host_greeting                                 30179 non-null  int64
 71  hot_tub_sauna_or_pool                         30179 non-null  int64
 72  internet                                      30179 non-null  int64
 73  long_term_stays                               30179 non-null  int64
 74  pets_allowed                                  30179 non-null  int64
 75  private_entrance                              30179 non-null  int64
 76  secure                                        30179 non-null  int64
 77  self_check_in                                 30179 non-null  int64
 78  smoking_allowed                               30179 non-null  int64
 79  accessible                                    30179 non-null  int64
 80  event_suitable                                30179 non-null  int64
dtypes: float64(16), int64(49), object(16)
memory usage: 18.7+ MB

In [8]:
airbnb_nyc.describe()

,id,host_id,host_since,host_response_rate,host_is_superhost,host_listings_count,host_identity_verified,latitude,longitude,accommodates,...,hot_tub_sauna_or_pool,internet,long_term_stays,pets_allowed,private_entrance,secure,self_check_in,smoking_allowed,accessible,event_suitable
count,3.017900e+04,3.017900e+04,30170.000000,17082.000000,30170.000000,30170.000000,30170.000000,30179.000000,30179.000000,30179.000000,...,30179.000000,30179.000000,30179.000000,30179.00000,30179.000000,30179.000000,30179.000000,30179.000000,30179.000000,30179.000000
mean,2.088031e+07,7.238659e+07,42160.939211,0.913360,0.083560,16.073285,0.487305,40.728593,-73.952292,2.723781,...,-0.902316,0.951887,-0.693893,-0.64134,-0.681898,-0.850028,-0.648696,-0.889460,-0.876470,-0.937838
std,1.090207e+07,8.296663e+07,841.819786,0.190183,0.276731,91.709777,0.499847,0.054541,0.044117,1.700634,...,0.431082,0.306454,0.720090,0.76727,0.731459,0.526746,0.761060,0.457021,0.481464,0.347080
min,2.539000e+03,2.787000e+03,39698.000000,0.000000,0.000000,0.000000,0.000000,40.499790,-74.244420,1.000000,...,-1.000000,-1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,1.127817e+07,9.165996e+06,41552.000000,0.910000,0.000000,1.000000,0.000000,40.690720,-73.982085,2.000000,...,-1.000000,1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
50%,2.175022e+07,3.314970e+07,42141.500000,1.000000,0.000000,1.000000,0.000000,40.721450,-73.955280,2.000000,...,-1.000000,1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
75%,3.093442e+07,1.168645e+08,42787.000000,1.000000,0.000000,2.000000,1.000000,40.762790,-73.936435,4.000000,...,-1.000000,1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
max,3.648724e+07,2.743213e+08,43653.000000,1.000000,1.000000,1070.000000,1.000000,40.913060,-73.716900,16.000000,...,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000